### ISSUE TITLE
Team overview

### ISSUE THREAD

**Issue by mholzi** [mholzi/home_trivia#77]
Of course. Here is a detailed plan to make the team overview in your Home Trivia game more graphically appealing.

### The Goal

The objective is to transform the current functional team overview into a more dynamic and visually engaging "leaderboard." We will achieve this by improving the visual hierarchy, adding animations, and using data visualization to make the scores more intuitive.

This plan focuses on modifying the `renderTeamsSection` function and adding CSS within the `home-trivia-card.js` file.

---

#### Step 1: Create a Dynamic Leaderboard Structure

Instead of a simple grid, we will restructure the display to give it a true leaderboard feel, with the first-place team being visually distinct.

1.  **Separate the Leader:** The top-ranked team will have a unique, larger card at the top, while the other teams will be listed below.
2.  **Visual Differentiation:** Use distinct styling for the top 3 positions (Gold, Silver, Bronze) to make the rankings immediately obvious.
3.  **Crown for the Leader:** Add a crown icon to the first-place team's card to signify their top position.

**Implementation (`renderTeamsSection` function in `home-trivia-card.js`):**

Modify the function to separate the first-place team from the rest.

```javascript
renderTeamsSection() {
    // ... (keep the existing logic for getting and sorting teams) ...
    const sortedTeams = allTeams.sort((a, b) => b.points - a.points);
    const leader = sortedTeams.length > 0 ? sortedTeams[0] : null;
    const otherTeams = sortedTeams.slice(1);

    let html = '<div class="leaderboard-container">';

    // Render the leader card
    if (leader) {
        html += `
            <div class="team-card leader-card rank-1">
                <ha-icon class="leader-crown" icon="mdi:crown"></ha-icon>
                <div class="team-name">${leader.name}</div>
                <div class="team-points">${leader.points} pts</div>
                // ... (add other status elements as needed) ...
            </div>
        `;
    }

    // Render the rest of the teams
    html += '<div class="other-teams-grid">';
    otherTeams.forEach((team, index) => {
        const rank = index + 2; // Rank starts from 2 for this list
        let cardClasses = `team-card rank-${rank}`;
        // ... (rest of the rendering logic for each card) ...
        html += `<div class="${cardClasses}"> ... </div>`;
    });
    html += '</div></div>';

    return html;
}
```

**New CSS (add to `<style>` block in `home-trivia-card.js`):**

```css
.leaderboard-container {
    padding: 16px 0;
}

.leader-card {
    border: 2px solid #ffd700; /* Gold border */
    background: linear-gradient(145deg, #fffbeb, #fdf2d1);
    transform: scale(1.05);
    margin-bottom: 24px;
    box-shadow: 0 8px 30px rgba(255, 215, 0, 0.3);
    position: relative;
}

.leader-crown {
    position: absolute;
    top: -15px;
    left: 50%;
    transform: translateX(-50%);
    font-size: 2em;
    color: #ffd700;
    filter: drop-shadow(0 2px 3px rgba(0,0,0,0.3));
}

.other-teams-grid {
    display: grid;
    gap: 12px;
}
```

#### Step 2: Visualize Scores with Progress Bars

A progress bar for each team provides an at-a-glance comparison of scores, making the competition feel tighter.

1.  **Calculate Max Score:** Find the highest score among all teams.
2.  **Render Progress Bars:** For each team, add a progress bar element. The width of the bar will be a percentage of their score relative to the max score.
3.  **Animate on Update:** Use CSS transitions to animate the progress bar's width when a team's score changes.

**Implementation (`renderTeamsSection` function):**

Inside the loop that renders each team card, add the progress bar.

```javascript
// Inside the forEach loop for rendering teams
const maxScore = leader ? leader.points : 1; // Get max score from the leader
const scorePercentage = Math.max(5, (team.points / maxScore) * 100); // Ensure a minimum width

html += `
    <div class="team-card rank-${rank}">
        <div class="team-info">
            <div class="team-rank">#${rank}</div>
            <div class="team-name">${team.name}</div>
        </div>
        <div class="team-score-section">
            <div class="team-points">${team.points} pts</div>
            <div class="score-progress-bar">
                <div class="score-progress-fill" style="width: ${scorePercentage}%;"></div>
            </div>
        </div>
    </div>
`;
```

**New CSS:**

```css
.team-score-section {
    grid-column: span 2; /* Make it span across the card */
    padding-top: 8px;
}

.score-progress-bar {
    width: 100%;
    height: 8px;
    background-color: #e2e8f0;
    border-radius: 4px;
    overflow: hidden;
    margin-top: 4px;
}

.score-progress-fill {
    height: 100%;
    background: linear-gradient(90deg, #60a5fa, #2563eb);
    border-radius: 4px;
    transition: width 0.5s ease-in-out;
}

.rank-1 .score-progress-fill { background: linear-gradient(90deg, #fde047, #f59e0b); }
.rank-2 .score-progress-fill { background: linear-gradient(90deg, #d1d5db, #9ca3af); }
.rank-3 .score-progress-fill { background: linear-gradient(90deg, #fcd34d, #d97706); }
```

#### Step 3: Add Meaningful Animations

Animations provide immediate visual feedback when the state of the game changes, making the experience more rewarding.

1.  **Animate Score Updates:** Use the existing `points-animator` class to show points flying to the score.
2.  **Animate Point Totals:** Make the point total for a team "flash" or "count up" when it's updated.
3.  **Animate Rank Changes:** If a team's rank changes, its card should animate to its new position in the list. (This is more complex and requires using a library like `lit` or a more advanced rendering strategy to track element positions). A simpler alternative is a "glow" effect.

**Implementation (CSS):**

Create CSS classes for these animations and apply them dynamically with JavaScript when a score update is detected in the `set hass` method.

**CSS Animations:**

```css
@keyframes score-update-flash {
    0% { background-color: #dbeafe; }
    100% { background-color: transparent; }
}

.score-updated {
    animation: score-update-flash 1s ease-out;
}

@keyframes count-up {
    from { transform: translateY(5px); opacity: 0.5; }
    to { transform: translateY(0); opacity: 1; }
}

.team-points {
    animation: count-up 0.3s ease-in-out;
}
```

**JavaScript (in `set hass`):**

```javascript
set hass(hass) {
    const previousHass = this._hass;
    this._hass = hass;

    if (previousHass) {
        for (let i = 1; i <= 5; i++) {
            const teamState = hass.states[`sensor.home_trivia_team_${i}`];
            const prevTeamState = previousHass.states[`sensor.home_trivia_team_${i}`];

            if (teamState && prevTeamState && teamState.attributes.points > prevTeamState.attributes.points) {
                // Find the card and apply the animation class
                const teamCard = this.shadowRoot.querySelector(`.team-card.team-${i}`);
                if (teamCard) {
                    teamCard.classList.add('score-updated');
                    setTimeout(() => teamCard.classList.remove('score-updated'), 1000);
                }
                // Also trigger the points flying animation
                this.triggerPointsAnimation(i, teamState.attributes.last_round_points);
            }
        }
    }
    // ... rest of the set hass logic ...
}
```
